### ISSUE TITLE
On some stories proofing window doesn't open

### ISSUE THREAD

**Issue by albuquezi** [ChapelR/poof#13]
Hi, 

I've been trying the poof 1.3 version with Twine 2.2.1 (desktop app) and I'm having some issues with some stories that get stuck on the loading circle when I try to access the proofing copy. I tried using the poof.config passage to put "parser" to false, but there is no change. I've attached one of the "troublesome" stories if you want to give a try.

Best

José

[NIRVANA 1.5 - J.Klimiuk, K.Marcinkiewicz, T. Duszyński.html.zip](https://github.com/ChapelR/poof/files/3360348/NIRVANA.1.5.-.J.Klimiuk.K.Marcinkiewicz.T.Duszynski.html.zip)

[Captura de ecrã 2019-07-04, às 21 38 06](https://user-images.githubusercontent.com/30144503/60685632-6d794500-9ea4-11e9-9119-6134ffc0293e.png)

**Comment by ChapelR** [comment]
Thanks I'll check it out.

**Comment by ChapelR** [comment]
Looks like it was just a typo, v1.3.1 should be live now at https://cdn.jsdelivr.net/gh/chapelr/poof@latest/docs/use/format.js 

Let me know if that fixes the issue.

**Comment by albuquezi** [comment]
Will do! The link still points to 1.3.0.

**Comment by ChapelR** [comment]
Ah. The latest link should update, soon. It's probably cached to your machine. Either way, whatever works.

**Comment by ChapelR** [comment]
P.S., I'd recommend using the specific version number, e.g., https://cdn.jsdelivr.net/gh/chapelr/poof@v1.3.1/docs/use/format.js rather than the development version, as there's no guarantee that version will always be working and recommended, since I use it to test new features.

**Comment by albuquezi** [comment]
Sure thing! Thanks!
