### ISSUE TITLE
Format 0.4.0 not working with tweego 1.3.0

### ISSUE THREAD

**Issue by antlas1** [ChapelR/poof#2]
Hello. I was trying to use new format with tweego compiler and have such exception:
```
    >tweego_x86.exe -f poof -o poof.html ../src
    warning: format poof: Skipping format; Could not decode JSON chunk.
    error: Story format "poof" is not available.
    Available formats:
      harlowe-1          > Harlowe (v1.2.4)
      harlowe-2          > Harlowe (v2.1.0)
      paperthin-1        > Paperthin (v1.0.0) [proofing]
      snowman-1          > Snowman (v1.3.0)
      sugarcube-1        > SugarCube (v1.0.35)
      sugarcube-2        > SugarCube (v2.27.0)`
```
Before running I'v been created directory "poof" in story-formats and copy format.js there. Version 0.0.1 (docs\use\poof-0-0-1.js) works well. I use OS win x64.

**Comment by ChapelR** [comment]
Tweego should be working again according to my tests. Thanks for letting me know. I should have tested Tweego before going live with it.
