### ISSUE TITLE
Poof 1.6.3 Continually Displays Loading Animation

### ISSUE THREAD

**Issue by lukellie** [ChapelR/poof#20]
Using Harlowe 2.1.0 and Poof 1.6.3 (which opens in Internet Explorer), I get the loading animation perpetually. The vertical and horizontal scroll bars continually change size, alternating where one is long and the other is short.
![image](https://user-images.githubusercontent.com/58856900/81007890-9c8b7a80-8e17-11ea-80fb-33db80967a84.png)

**Comment by ChapelR** [comment]
Poof does not support internet explorer.
