### ISSUE TITLE
PDF export not working for big stories

### ISSUE THREAD

**Issue by albuquezi** [ChapelR/poof#5]
When I try to export a big story to PDF (around 8000 words), the PDF gets created but all the pages are blank. I've tried to use both the installed version (Windows) and the online version. Same result.

**Comment by ChapelR** [comment]
I'll look into this, but it may be a limitation of the canvas, which means it may not get a fast fix. My theory is that large stories wind up being larger than the canvas used to stage the PDF file. Canvases apparently have hard height and width limits of around 32,000 pixels, which I didn't know beforehand. This means that I need to develop some way to read this size and split the file into multiple canvases, then stitch those together into a PDF. Which is gonna be gross.

**Comment by ChapelR** [comment]
I believe I've fixed this by avoiding using a canvas altogether. An official release with the fix will be forthcoming. Are you able to do some testing for me?

**Comment by albuquezi** [comment]
Great! Sure! I'll look into this evening and will let you know.

José

A quarta, 3/04/2019, 17:01, Chapel <notifications@github.com> escreveu:

**Comment by ChapelR** [comment]
Just grab the new version from the dist folder.

**Comment by albuquezi** [comment]
It works fine now. I threw Agnieszka Trzaska’s “Lux” at it

https://ifdb.tads.org/viewgame?id=rg7sieqyg1b9rxpt

 

which has 55422 words, according to Twine, and I got a 311 page PDF file. So that should mean the solution is robust 😊

 

And the text is now text and not an image like before, which is better. 

 

Is there any chance to add some PDF config options like choice and size of font or line spacing?

**Comment by ChapelR** [comment]
Configuration for the pdf could probably, at least in a limited manner, be added. Probably via `poof.config`. 

About how long did the pdf file take to generate for you? I don't need an exact time or anything, but did it take a few seconds, thirty seconds, a minute?

**Comment by albuquezi** [comment]
The 8000 words story about 3 seconds (50 PDF pages), and the 55000 words (311 PDF pages ), about 7 seconds. I think it’s quite good.

**Comment by ChapelR** [comment]
Great, thanks so much for the help!

**Comment by albuquezi** [comment]
My pleasure! Thank you for doing this for the community!
