### ISSUE TITLE
PDF options not working

### ISSUE THREAD

**Issue by albuquezi** [ChapelR/poof#8]
I've tried to format the PDF export version via the poof.config passage, but I always get a PDF with the same formatting, the default formatting values, I'm assuming. 
Neither one of the three PDF options seems to affect the PDF export.

The options for the poof window are working though, night mode and fonts, at least.

**Comment by ChapelR** [comment]
Hmm. It worked in testing. I'll look into this when I have time later in the week. Thanks to the heads up.

**Comment by albuquezi** [comment]
Yesterday, I tried only in my windows machine. I'll try my Mac today, and double check everything.
Em 30/04/2019, 16:49 +0200, Chapel <notifications@github.com>, escreveu:

**Comment by albuquezi** [comment]
So it seems that the problem is with version 2.2.1 of Twine, which was the one I still had installed. I installed 2.3.1 and everything seems to be working fine. Great, in fact. Thanks for doing this! It's a really important plugin for me. It makes my life so much easier when I have to correct texts.

**Comment by ChapelR** [comment]
I'll look into it anyway, since it should work with 2.2.1, but I'm glad it's at least working in the current version.

**Comment by ChapelR** [comment]
I seen to be unable to recreate this issue in Twine 2.2.1, so for now I'm closing this. Might have been some weird caching issue with Twine or the CDN.
